name: Build KernelSU Next Vayu
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Kernel
        uses: dabao1955/kernel_build_action@main
        with:
          kernel-url: https://github.com/LuffyTaro008/android_kernel_xiaomi_vayu
          kernel-branch: 13
          config: vayu_defconfig
          arch: arm64
          android-version: 12
          aosp-clang: true
          aosp-gcc: true
          # Cấu hình mạnh tay hơn để sửa lỗi khởi tạo biến
          extra-make-args: |
            [
              "LLVM=1",
              "LLVM_IAS=1",
              "KCFLAGS=-w -Xclang -enable-trivial-auto-var-init-zero-knowing-it-will-be-removed-from-clang",
              "HOSTCFLAGS=-Xclang -enable-trivial-auto-var-init-zero-knowing-it-will-be-removed-from-clang"
            ]
          ksu: true
          ksu-other: true
          ksu-url: https://github.com/tiann/KernelSU
          anykernel3: true
          release: true
          access-token: ${{ secrets.GITHUB_TOKEN }}
