name: CI
on:
  push:
    branches: main
    paths:
      - '.github/workflows/main.yml'
      - 'action.yml'
      - 'src/**/*.ts'
      - 'package.json'
      - 'yarn.lock'
  pull_request:
    paths:
      - '.github/workflows/main.yml'
      - 'action.yml'
      - 'src/**/*.ts'
      - 'package.json'
      - 'yarn.lock'
  workflow_dispatch:

jobs:
  ci-test:
    name: Build Kernel
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Kernel
        uses: ./
        with:
          # Link repo bạn đã Fork về tài khoản cá nhân
          kernel-url: https://github.com/khangsv23/android_kernel_xiaomi_vayu
          kernel-dir: msm-4.14
          # Nhánh misc đã xác định trong ảnh trước
          kernel-branch: misc
          # File config chuẩn cho Poco X3 Pro
          config: vayu_user_defconfig
          arch: arm64
          aosp-gcc: true
          aosp-clang: true
          ksu: true
          ksu-version: main
          android-version: 12
          aosp-clang-version: r383902
          disable-lto: true
          anykernel3: true
