name: Build KernelSU Next Vayu
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Kernel
        uses: dabao1955/kernel_build_action@main
with:
          kernel-url: https://github.com/LuffyTaro008/android_kernel_xiaomi_vayu
          kernel-branch: 13
          config: vayu_defconfig
          arch: arm64
          android-version: 11 # Hạ xuống Android 11 để dùng Clang đời cũ hơn
          aosp-clang: true
          aosp-gcc: true
          extra-make-args: '["LLVM=1", "LLVM_IAS=1", "KCFLAGS=-w"]'
          ksu: true
          ksu-other: true
          ksu-url: https://github.com/tiann/KernelSU
          anykernel3: true
          release: true
          access-token: ${{ secrets.GITHUB_TOKEN }}
